"""
School Research Assistant - Pydantic Models (v2)
================================================
Replaces: models.py (dataclasses)

WHY PYDANTIC?
- Automatic validation (if GPT returns bad data, we catch it immediately)
- Easy JSON serialization (for caching and export)
- Works seamlessly with LangChain structured outputs
- Clear error messages when data is wrong

WHAT THIS FILE DOES:
- Defines the structure of all data in the app
- Validates data automatically when created
- Provides default values for missing fields
"""

from pydantic import BaseModel, Field, EmailStr, field_validator
from typing import Optional, List, Dict, Any
from datetime import datetime
from enum import Enum


class ContactRole(str, Enum):
    """Types of contacts we track"""
    HEADTEACHER = "headteacher"
    DEPUTY_HEAD = "deputy_head"
    ASSISTANT_HEAD = "assistant_head"
    BUSINESS_MANAGER = "business_manager"
    SENCO = "senco"
    UNKNOWN = "unknown"


class Contact(BaseModel):
    """
    A school contact (headteacher, deputy, etc.)
    
    Example:
        Contact(
            full_name="Ms Perina Holness",
            role=ContactRole.HEADTEACHER,
            title="Ms",
            first_name="Perina",
            last_name="Holness",
            email="pholness@school.sch.uk",
            phone="020 7520 0385"
        )
    """
    full_name: str = Field(description="Full name of the contact")
    role: ContactRole = Field(default=ContactRole.UNKNOWN, description="Their role at the school")
    title: Optional[str] = Field(default=None, description="Mr, Ms, Mrs, Dr, etc.")
    first_name: Optional[str] = Field(default=None)
    last_name: Optional[str] = Field(default=None)
    email: Optional[str] = Field(default=None, description="Email address if known")
    phone: Optional[str] = Field(default=None, description="Phone number")
    confidence_score: float = Field(default=1.0, ge=0.0, le=1.0, description="How confident we are in this data (0-1)")
    
    @field_validator('phone', mode='before')
    @classmethod
    def clean_phone(cls, v):
        """Clean phone number - remove .0 from float conversion"""
        if v is None:
            return None
        v = str(v)
        if v.endswith('.0'):
            v = v[:-2]
        # Format UK phone numbers
        if v.startswith('20') and len(v) == 10:
            v = f"020 {v[2:6]} {v[6:]}"
        return v


class FinancialData(BaseModel):
    """
    School financial data from government sources
    
    All values are stored as strings (e.g., "£4,100 per pupil") 
    for easy display and LLM processing.
    """
    total_teaching_support_spend_per_pupil: Optional[str] = Field(
        default=None, 
        description="Total spend on teaching and support staff per pupil"
    )
    comparison_to_other_schools: Optional[str] = Field(
        default=None,
        description="How this school compares to similar schools"
    )
    total_teaching_support_per_pupil: Optional[str] = Field(default=None)
    teaching_staff_costs: Optional[str] = Field(default=None)
    supply_teaching_costs: Optional[str] = Field(default=None)
    agency_supply_costs: Optional[str] = Field(
        default=None,
        description="CRITICAL: Agency supply costs - key sales metric"
    )
    educational_support_costs: Optional[str] = Field(default=None)
    educational_consultancy_costs: Optional[str] = Field(default=None)
    
    def has_agency_spend(self) -> bool:
        """Check if school spends on agency staff (sales opportunity)"""
        if not self.agency_supply_costs:
            return False
        # Check if it's not "£0 per pupil"
        return "£0" not in self.agency_supply_costs
    
    def get_priority_level(self) -> str:
        """Extract priority level from spend data"""
        if self.total_teaching_support_spend_per_pupil:
            if "High priority" in self.total_teaching_support_spend_per_pupil:
                return "HIGH"
            elif "Medium priority" in self.total_teaching_support_spend_per_pupil:
                return "MEDIUM"
            elif "Low priority" in self.total_teaching_support_spend_per_pupil:
                return "LOW"
        return "UNKNOWN"


class OfstedData(BaseModel):
    """Ofsted inspection data"""
    rating: Optional[str] = Field(default=None, description="Outstanding, Good, Requires Improvement, Inadequate")
    inspection_date: Optional[str] = Field(default=None)
    report_url: Optional[str] = Field(default=None)
    areas_for_improvement: List[str] = Field(default_factory=list)
    key_strengths: List[str] = Field(default_factory=list)


class ConversationStarter(BaseModel):
    """
    A talking point for sales consultants
    
    Generated by the LLM based on school data.
    """
    topic: str = Field(description="Brief topic heading")
    detail: str = Field(description="The actual conversation starter script")
    source: Optional[str] = Field(default=None, description="Where this insight came from")
    relevance_score: float = Field(default=0.8, ge=0.0, le=1.0)
    
    class Config:
        json_schema_extra = {
            "example": {
                "topic": "High Agency Spend",
                "detail": "I noticed from government data that you're spending £604 per pupil on agency supply staff, which is higher than 66% of similar schools. We've helped schools like yours reduce these costs by 20% while improving teacher quality. Would you be open to a brief conversation about how?",
                "source": "Financial Benchmarking Data",
                "relevance_score": 0.95
            }
        }


class School(BaseModel):
    """
    Complete school record
    
    This is the main data structure. One School object contains
    everything we know about a school.
    """
    # Identifiers
    urn: str = Field(description="Unique Reference Number - the school's ID")
    school_name: str = Field(description="Official school name")
    
    # Location
    la_name: Optional[str] = Field(default=None, description="Local Authority name")
    address_1: Optional[str] = Field(default=None)
    address_2: Optional[str] = Field(default=None)
    address_3: Optional[str] = Field(default=None)
    town: Optional[str] = Field(default=None)
    county: Optional[str] = Field(default=None)
    postcode: Optional[str] = Field(default=None)
    
    # School type
    school_type: Optional[str] = Field(default=None, description="Academy, Community school, etc.")
    phase: Optional[str] = Field(default=None, description="Primary, Secondary, Nursery, etc.")
    pupil_count: Optional[int] = Field(default=None)
    
    # Trust info
    trust_code: Optional[str] = Field(default=None)
    trust_name: Optional[str] = Field(default=None)
    
    # Contact info
    phone: Optional[str] = Field(default=None)
    website: Optional[str] = Field(default=None)
    
    # Key contacts
    headteacher: Optional[Contact] = Field(default=None)
    contacts: List[Contact] = Field(default_factory=list)
    
    # Financial data
    financial: Optional[FinancialData] = Field(default=None)
    
    # Ofsted data
    ofsted: Optional[OfstedData] = Field(default=None)
    
    # Generated insights
    conversation_starters: List[ConversationStarter] = Field(default_factory=list)
    
    # Metadata
    last_updated: datetime = Field(default_factory=datetime.now)
    data_source: str = Field(default="csv", description="csv, databricks, or live")
    
    @field_validator('pupil_count', mode='before')
    @classmethod
    def parse_pupil_count(cls, v):
        """Convert pupil count to integer"""
        if v is None or v == '':
            return None
        try:
            return int(float(v))
        except (ValueError, TypeError):
            return None
    
    @field_validator('phone', mode='before')
    @classmethod
    def clean_phone(cls, v):
        """Clean phone number format"""
        if v is None:
            return None
        v = str(v)
        if v.endswith('.0'):
            v = v[:-2]
        return v
    
    def get_full_address(self) -> str:
        """Combine address fields into single string"""
        parts = [
            self.address_1, 
            self.address_2, 
            self.address_3, 
            self.town, 
            self.county, 
            self.postcode
        ]
        return ", ".join([p for p in parts if p])
    
    def get_sales_priority(self) -> str:
        """Determine sales priority based on financial data"""
        if not self.financial:
            return "UNKNOWN"
        return self.financial.get_priority_level()
    
    def to_llm_context(self) -> str:
        """
        Convert school data to text format for LLM analysis.
        This is what gets sent to Claude/GPT to generate conversation starters.
        """
        lines = [
            f"SCHOOL: {self.school_name}",
            f"URN: {self.urn}",
            f"Type: {self.school_type or 'Unknown'} ({self.phase or 'Unknown phase'})",
            f"Location: {self.get_full_address()}",
            f"Pupil Count: {self.pupil_count or 'Unknown'}",
        ]
        
        # Add headteacher info
        if self.headteacher:
            lines.append(f"\nHEADTEACHER: {self.headteacher.full_name}")
            if self.headteacher.phone:
                lines.append(f"Phone: {self.headteacher.phone}")
        
        # Add financial data
        if self.financial:
            lines.append("\nFINANCIAL DATA:")
            if self.financial.total_teaching_support_spend_per_pupil:
                lines.append(f"Total Teaching & Support Spend: {self.financial.total_teaching_support_spend_per_pupil}")
            if self.financial.comparison_to_other_schools:
                lines.append(f"Comparison: {self.financial.comparison_to_other_schools}")
            if self.financial.agency_supply_costs:
                lines.append(f"Agency Supply Costs: {self.financial.agency_supply_costs}")
            if self.financial.educational_consultancy_costs:
                lines.append(f"Consultancy Costs: {self.financial.educational_consultancy_costs}")
        
        # Add Ofsted data
        if self.ofsted:
            lines.append(f"\nOFSTED RATING: {self.ofsted.rating or 'Unknown'}")
            if self.ofsted.areas_for_improvement:
                lines.append("Areas for improvement:")
                for area in self.ofsted.areas_for_improvement:
                    lines.append(f"  - {area}")
        
        return "\n".join(lines)


class SchoolSearchResult(BaseModel):
    """Result from searching for schools"""
    schools: List[School] = Field(default_factory=list)
    total_count: int = Field(default=0)
    query: Optional[str] = Field(default=None)


class ConversationStarterResponse(BaseModel):
    """
    Response from the LLM when generating conversation starters.
    
    This is used by LangChain to parse the LLM output into structured data.
    """
    conversation_starters: List[ConversationStarter] = Field(
        description="List of conversation starters for sales consultants"
    )
    summary: Optional[str] = Field(
        default=None,
        description="Brief summary of the school's key characteristics"
    )
    sales_priority: str = Field(
        default="MEDIUM",
        description="HIGH, MEDIUM, or LOW priority for sales outreach"
    )
